application:
  swagger2:
    version: 1.0
    title: 小贷商城-内容中心-Swagger2接口文档
    description:
    contact:
      email: sdzy890819@126.com
      name: Zhang Yang
      url: https://github.com/sdzy890819/servecenter
    terms-url: http://xxxxxxxxxxxxxx