application:
  swagger2:
    version: 1.0
    title: 藕丁钱包-订单中心-Swagger2接口文档
    description:
    contact:
      email: zhangyang@ouding.com
      name: Zhang Yang
      url: http://118.190.88.132/zhangyang/wallet
    terms-url: xx